### PR TITLE
New resource UML pic

### PR DESCRIPTION
**Pull request by fosterlynn**
For discussion, not looking for merge necessarily, although it probably reflects where we are at better than the existing one. This is mostly an attempt to document what we have thus far.   I'd like a reading on what are our remaining issues on vf:Resource, and/or issues with this model.  And I do expect there is still some discussion on what I have here. :)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
Thank you @fosterlynn 
1. I don't think we use _qudt:quantity_ directly on the resource but on the value of _vf:quantity_. 
2. vf:WorkResource seems like subclass of vf:ServiceResource and represents special case where a single person does the work of providing service.
3. Should we add _vf:category_ or _vf:kind_ to both _vf:Resource_ and _vf:ResourceModel_ ?

I think we can almost merge it :)

**Comment by elf-pavlik** [comment]
Actually if we have _vf:TimeBasedResource_ than _vf:WorkResource_ could have two parent classes _vf:ServiceResource_ and _vf:TimeBasedResource_.

**Comment by fosterlynn** [comment]
> I don't think we use qudt:quantity directly on the resource but on the value of vf:quantity. 

Have vf:quantity.  But you are probably thinking of qudt:unit.  How best to handle that?  vf:unit?

> vf:WorkResource seems like subclass of vf:ServiceResource and represents special case where a single person does the work of providing service.

I still disagree with equating service with work.  How would you create the vf:ServiceResource, if not with some work?  And possibly some other inputs?  We have already used vf:ServiceResource as an output from a process (transporting bikes) so it can be used in a transfer for exchange, or as an input to a process.  A service seems more like a package result than just actual observable work, more like a deliverable, would often not have unit of Hours.  If a person has other inputs that are worth logging (like a laptop or space, say in case of the VF meeting), that would also be input to whichever process that inputs the work, whether one creating a service that will be input, or the other process directly.

> Actually if we have vf:TimeBasedResource than vf:WorkResource could have two parent classes vf:ServiceResource and vf:TimeBasedResource.

Hmmm.  There are differences in vf:UsageResource and vf:WorkResource.  So maybe vf:TimeBasedResource isn't a good idea for now?  (In this comment, I'm still assuming vf:ServiceResource is not a time based resource.  It is more like "one dental service".)

> Should we add vf:category or vf:kind to both vf:Resource and vf:ResourceModel ?

vf:category is on vf:Resource, makes sense to also add to vf:ResourceModel.

**Comment by fosterlynn** [comment]
Committed a new picture with the couple suggested changes.  Haven't done anything about work vs service, pending further discussion.

**Comment by elf-pavlik** [comment]
Okie dokie! Looks like we have an improved diagram, let's take some to clarify mentioned topic and we will address them in future PRs.

**Pull request merged**
