### PR TITLE
included resource uml diagram

### PR DESCRIPTION
**Pull request by fosterlynn**
first cut resource and resource type, uml (sorry)

### CODE REVIEW

**Comment by gcassel** [comment]
It looks great to me, but probably Bob Elf or Mikey should verify :)

**Comment by elf-pavlik** [comment]
I would like to propose to always use **namespace**. This way we can write **vf:Resource** which implies it as **Economic Resource**. This way we can avoid getting stuck on does Transfer mean this or that and always precisely talk about **vf:Transfer** as defined in vf namespace.

**Comment by bhaugen** [comment]
Ok, I will try to comply. Might forget now and then at first. Willing to be corrected.

**Comment by elf-pavlik** [comment]
@fosterlynn you introduced **Work** in this diagram. Could you make another PR with Work.md and first draft of its definition?

**Comment by fosterlynn** [comment]
@elf-pavlik will do.  Might be later this week.

Also, I think the Resource model is in flux, I like where you are going with it, so probably will re-do that too.

**Comment by elf-pavlik** [comment]
thanks @fosterlynn & no rush!
could you please also create Resource.md and explain there _vf:underlyingResource_ relation(ship)

**Comment by fosterlynn** [comment]
> @fosterlynn you introduced Work in this diagram. Could you make another PR with Work.md and first draft of its definition?

Actually, not work but type of work as a subclass of resource type.  So that people can define skills or work roles that they want to value differently or report on.

But I'll take a whole bigger look at Resource and Resource Type, and re-do this, plus some work on the README.md file.

**Pull request merged**
